### ISSUE TITLE
Avoid creating an Azure dependency for on prem requesting public DNS.

### ISSUE THREAD

**Issue by chboudry** [dmauser/PrivateLink#9]
First, this doc is superb, and it is my go-to every time I need to explain DNS to customers. Thank you very much for the work.

Might I suggest a small improvement on the onprem/private dns resovler architecture: 
https://github.com/dmauser/PrivateLink/tree/master/DNS-Integration-Scenarios#41-azure-dns-private-resolver-preview

I had a scenario where customer was using a small Azure infra and a big on-prem one, meaning: 
- a lot of on prem dns requests target windows.net & co but are not about Azure
- on-prem team does not want to make those requests dependent of the azure infra & DNS resolver (Yes SLA on Azure DNs is 100%, but this is not true for VPN/ER + private resolver)

To solve this scenario then the on-prem forwarder would not be on blob.core.windows.net but on privatelink.blob.core.windows.net.
Of course, end customer still queries FQDN of the official PAAS service to comply with SNI.

This way first request goes directly from on prem DNS to DNS authoritative on the internet. 
And then and only then use the forwarder to resolve the private one.

That way you don't make on prem dependent of your Azure infra for public stuff, but only for Azure private infra one, which actually makes much more sense.

**Comment by dmauser** [comment]
Thanks for your input @chboudry. I mainly added blob.core.windows.net as a conditional forwarder because Windows DNS has a different behavior than BIND-based DNS servers. If the On-premises Windows DNS Server uses Global Forwarders, it will not honor the conditional forwarder to privatelink.blob.core.windows.net. The only way to make that work on Windows DNS is to use plain root hints (not Global Forwarders). In the same article, I added a detailed explanation of this behavior: https://github.com/dmauser/PrivateLink/tree/master/DNS-Integration-Scenarios#43-on-premises-dns-server-conditional-forwarder-considerations

**Comment by chboudry** [comment]
I should have read more carefully this part of the article ;) 
Fortunately, I did not encounter that as my customer was not using Windows DNS.
Thanks !
